CREATE TABLE ITEMS (
    ITEM_ID NUMBER(5, 0),
    ITEM_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER(3, 2) NOT NULL,
    RESTAURANT_ID NUMBER(5, 0),
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEM_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);