CREATE SEQUENCE USER_ID_GENERATOR START WITH 1;
CREATE SEQUENCE TOKEN_ID_GENERATOR START WITH 1;
CREATE SEQUENCE LINE_ITEMS_ID_GENERATOR START WITH 1;
CREATE SEQUENCE ORDER_ID_GENERATOR START WITH 1;
