CREATE TABLE ORDERS (
    ORDER_ID NUMBER(5, 0) DEFAULT ORDER_ID_GENERATOR.NEXTVAL,
    PLACED_AT DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    TOTAL NUMBER(5, 2),
    CORRELATION_ID VARCHAR2(100) NOT NULL,
    DELIVERY_TIME DATE,
    USER_ID NUMBER(5, 0),
    RESTAURANT_ID NUMBER(5, 0),
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT ORDER_US_FK FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT ORDER_REST_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);